<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AdaptAula.Domain\AdaptAula.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data/measure-library.json" LogicalName="measure-library.json" />
    <EmbeddedResource Include="Data/curriculum/*.json" LogicalName="curriculum/%(Filename)%(Extension)" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
